var annotated_dup =
[
    [ "tinyxml2", null, [
      [ "StrPair", "classtinyxml2_1_1_str_pair.html", "classtinyxml2_1_1_str_pair" ],
      [ "DynArray", "classtinyxml2_1_1_dyn_array.html", "classtinyxml2_1_1_dyn_array" ],
      [ "MemPool", "classtinyxml2_1_1_mem_pool.html", "classtinyxml2_1_1_mem_pool" ],
      [ "MemPoolT", "classtinyxml2_1_1_mem_pool_t.html", "classtinyxml2_1_1_mem_pool_t" ],
      [ "XMLVisitor", "classtinyxml2_1_1_x_m_l_visitor.html", "classtinyxml2_1_1_x_m_l_visitor" ],
      [ "XMLUtil", "classtinyxml2_1_1_x_m_l_util.html", null ],
      [ "XMLNode", "classtinyxml2_1_1_x_m_l_node.html", "classtinyxml2_1_1_x_m_l_node" ],
      [ "XMLText", "classtinyxml2_1_1_x_m_l_text.html", "classtinyxml2_1_1_x_m_l_text" ],
      [ "XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", "classtinyxml2_1_1_x_m_l_comment" ],
      [ "XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", "classtinyxml2_1_1_x_m_l_declaration" ],
      [ "XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", "classtinyxml2_1_1_x_m_l_unknown" ],
      [ "XMLAttribute", "classtinyxml2_1_1_x_m_l_attribute.html", "classtinyxml2_1_1_x_m_l_attribute" ],
      [ "XMLElement", "classtinyxml2_1_1_x_m_l_element.html", "classtinyxml2_1_1_x_m_l_element" ],
      [ "XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", "classtinyxml2_1_1_x_m_l_document" ],
      [ "XMLHandle", "classtinyxml2_1_1_x_m_l_handle.html", "classtinyxml2_1_1_x_m_l_handle" ],
      [ "XMLConstHandle", "classtinyxml2_1_1_x_m_l_const_handle.html", "classtinyxml2_1_1_x_m_l_const_handle" ],
      [ "XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", "classtinyxml2_1_1_x_m_l_printer" ],
      [ "Entity", "structtinyxml2_1_1_entity.html", "structtinyxml2_1_1_entity" ]
    ] ],
    [ "tmxparser", null, [
      [ "TmxRect", "structtmxparser_1_1_tmx_rect.html", "structtmxparser_1_1_tmx_rect" ],
      [ "TmxProperty", "structtmxparser_1_1_tmx_property.html", "structtmxparser_1_1_tmx_property" ],
      [ "TmxAnimationFrame", "structtmxparser_1_1_tmx_animation_frame.html", "structtmxparser_1_1_tmx_animation_frame" ],
      [ "TmxObject", "structtmxparser_1_1_tmx_object.html", "structtmxparser_1_1_tmx_object" ],
      [ "TmxObjectGroup", "structtmxparser_1_1_tmx_object_group.html", "structtmxparser_1_1_tmx_object_group" ],
      [ "TmxOffset", "structtmxparser_1_1_tmx_offset.html", "structtmxparser_1_1_tmx_offset" ],
      [ "TmxImage", "structtmxparser_1_1_tmx_image.html", "structtmxparser_1_1_tmx_image" ],
      [ "TmxImageLayer", "structtmxparser_1_1_tmx_image_layer.html", "structtmxparser_1_1_tmx_image_layer" ],
      [ "TmxTileDefinition", "structtmxparser_1_1_tmx_tile_definition.html", "structtmxparser_1_1_tmx_tile_definition" ],
      [ "TmxTileset", "structtmxparser_1_1_tmx_tileset.html", "structtmxparser_1_1_tmx_tileset" ],
      [ "TmxLayerTile", "structtmxparser_1_1_tmx_layer_tile.html", "structtmxparser_1_1_tmx_layer_tile" ],
      [ "TmxLayer", "structtmxparser_1_1_tmx_layer.html", "structtmxparser_1_1_tmx_layer" ],
      [ "TmxMap", "structtmxparser_1_1_tmx_map.html", "structtmxparser_1_1_tmx_map" ]
    ] ],
    [ "CEngine", "class_c_engine.html", "class_c_engine" ],
    [ "CEntity", "class_c_entity.html", "class_c_entity" ],
    [ "CItemPushable", "class_c_item_pushable.html", "class_c_item_pushable" ],
    [ "CLayer", "class_c_layer.html", "class_c_layer" ],
    [ "CPlayer", "class_c_player.html", "class_c_player" ],
    [ "CSprite", "class_c_sprite.html", "class_c_sprite" ],
    [ "CTile", "class_c_tile.html", "class_c_tile" ],
    [ "CTileMap", "class_c_tile_map.html", "class_c_tile_map" ],
    [ "cVideo", "classc_video.html", "classc_video" ],
    [ "CVideoSystemDefault", "class_c_video_system_default.html", "class_c_video_system_default" ],
    [ "CWorld", "class_c_world.html", "class_c_world" ],
    [ "ITimer", "class_i_timer.html", "class_i_timer" ],
    [ "ITimerWindows", "class_i_timer_windows.html", "class_i_timer_windows" ],
    [ "IVideoSystem", "class_i_video_system.html", "class_i_video_system" ],
    [ "Map", "struct_map.html", "struct_map" ],
    [ "Rect", "struct_rect.html", "struct_rect" ],
    [ "sRGB", "structs_r_g_b.html", "structs_r_g_b" ],
    [ "STileProperties", "struct_s_tile_properties.html", "struct_s_tile_properties" ],
    [ "utils", "classutils.html", null ],
    [ "Vec2D", "struct_vec2_d.html", "struct_vec2_d" ],
    [ "Vec3D", "struct_vec3_d.html", "struct_vec3_d" ],
    [ "Vec3Df", "struct_vec3_df.html", "struct_vec3_df" ],
    [ "ViewPort", "struct_view_port.html", "struct_view_port" ]
];